debug: false
msg:
  prefix: '&7[&cFreezeKill&7]'
  noperm: '&c/You do not have enough access privileges for this operation.'
cmd:
  - 'true,say this command is executed by console'
  - 'false,kill'
  - 'true,say that kill command was executed by %player%'
  - 'true,say % player % gets replaced by the playername ...'
  - 'true,say you can add more commands easily ...'
