name: FreezeKill
main: FreezeKill
description: requested plugin made by undeaD_D
version: 3.0
author: DieFriiks
authors: [DieFriiks, undeaD_D]
databse: false

commands:
  freezekill:
    usage: /freezekill <reload/unfreeze/[time]>
    description: FreezeKill commands
